version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.23.0
    - 7.25.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.13.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.10
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.4
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.8.0
  - dependency-name: "@babel/eslint-parser"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.4
    - 7.13.8
